### ISSUE TITLE
Create Dockerfile [server]

### ISSUE THREAD

**Issue by roselis-lab** [SUAI-Smart-Space-Team/smart-edge-server#1]
1) What are global variables and whats their values?
2) Is there any dynamic service - DB, for example, running here?

**Comment by Chubru** [comment]
1)I do not understand, what do you mean under "global variables" term. The smart smart-edge-server does not use global variables like it is defined in C/C++. The smart-edge-server uses environments variables comes from HTTP server. Such as post/get parameters and http-referer
